apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: easy-webapp
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: helm
    repoURL: https://github.com/francisco-codefresh/easy-webapp.git
    targetRevision: master
    helm:
      values: |
{{ toYaml (index .Values "easy-webapp") | indent 8 }}
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true