apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temp-webapp-{{ include "helm.name" . }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: helm
    repoURL: https://github.com/francisco-codefresh/easy-webapp.git
    targetRevision: master
    helm:
      valuesFiles:
      - https://raw.githubusercontent.com/francisco-codefresh/blog-environments/master/staging/helm/values-temp-webapp.yaml
      version: v3
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true